
after_success: 
  
  - "find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3\" \"$4\" \"$5}'"
dist: trusty
env: 
  - COVERAGE=0.3 ./gradlew test jacocoTestCoverageVerification
  - COVERAGE=0.5 ./gradlew -p ./monolithic/ui check
  - COVERAGE=0.5 ./gradlew -p ./monolithic/service/cart check
  - COVERAGE=0.5 ./gradlew -p ./monolithic/service/user check
  - COVERAGE=0.5 ./gradlew -p ./monolithic/repository/order check
  - COVERAGE=0.5 ./gradlew -p ./monolithic/repository/cart check
  - COVERAGE=0.5 ./gradlew -p ./monolithic/repository/product check
  - COVERAGE=0.5 ./gradlew -p ./monolithic/repository/user check
jdk: 
- oraclejdk8
- oraclejdk9
language: java
script: 
  - "./gradlew clean jar"
  
