--- 
after_success: 
  - "./gradlew jacocoTestReport"
  - "find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3\" \"$4\" \"$5}'"
  - "./gradlew test jacocoTestCoverageVerification"
  - "if [ $COVERAGE< 0.35 ]; then exit 1 ; fi ;"
dist: trusty
env: 
  - "COVERAGE= 0.35 ./gradlew test jacocoTestCoverageVerification"
jdk: oraclejdk8
language: java
script: 
  - "./gradlew clean jar"
  - "./gradlew test"
